package io.github.aedev.flow.player.stream

import android.net.Uri
import android.util.Log
import io.github.aedev.flow.innertube.models.response.PlayerResponse
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.SubtitlesStream

object CaptionTrackResolver {
    private const val TAG = "CaptionTrackResolver"

    private val AUTO_TRANSLATE_TARGETS = listOf(
        "en", "es", "fr", "de", "pt", "it", "ru", "ja", "ko", "zh",
        "ar", "hi", "bn", "nl", "pl", "tr", "vi", "th", "id"
    )

    fun resolve(playerResponse: PlayerResponse): List<SubtitlesStream> {
        val renderer = playerResponse.captions?.playerCaptionsTracklistRenderer ?: return emptyList()
        val tracks = renderer.captionTracks?.filter { !it.baseUrl.isNullOrBlank() && !it.languageCode.isNullOrBlank() }
            .orEmpty()
        if (tracks.isEmpty()) return emptyList()

        val result = mutableListOf<SubtitlesStream>()

        tracks.forEach { track ->
            val isAsr = track.kind == "asr"
            buildStream(track.baseUrl!!, track.languageCode!!, autoGenerated = isAsr)?.let { result.add(it) }
        }

        val translatableTrack = tracks.firstOrNull { it.isTranslatable == true }
        if (translatableTrack != null) {
            val available = renderer.translationLanguages
                ?.mapNotNull { it.languageCode }
                ?.toSet()
                ?: emptySet()
            val nativeCodes = tracks.mapNotNull { it.languageCode }.toSet()
            AUTO_TRANSLATE_TARGETS
                .filter { it in available && it !in nativeCodes }
                .forEach { target ->
                    val url = appendQueryParam(translatableTrack.baseUrl!!, "tlang", target)
                    buildStream(url, target, autoGenerated = true)?.let { result.add(it) }
                }
        }

        Log.d(TAG, "Resolved ${result.size} caption tracks (${tracks.size} native) from InnerTube captions")
        return result
    }

    private fun buildStream(baseUrl: String, languageCode: String, autoGenerated: Boolean): SubtitlesStream? {
        return try {
            SubtitlesStream.Builder()
                .setContent(appendQueryParam(baseUrl, "fmt", "vtt"), true)
                .setMediaFormat(MediaFormat.VTT)
                .setLanguageCode(languageCode)
                .setAutoGenerated(autoGenerated)
                .build()
        } catch (e: Exception) {
            Log.w(TAG, "Failed to build SubtitlesStream for $languageCode: ${e.message}")
            null
        }
    }

    private fun appendQueryParam(url: String, key: String, value: String): String {
        return try {
            Uri.parse(url).buildUpon().appendQueryParameter(key, value).build().toString()
        } catch (e: Exception) {
            val sep = if (url.contains('?')) '&' else '?'
            "$url$sep$key=$value"
        }
    }
}
