package com.omersusin.pitube.data

data class VideoItem(
    val url: String,
    val title: String,
    val thumbnailUrl: String?,
    val uploaderName: String,
    val uploaderAvatar: String?,
    val uploaderUrl: String? = null,
    val duration: Int,
    val views: Long,
    val uploadedDate: String?,
    val isShort: Boolean = false,
    val channelId: String? = null,
    val channelIconUrl: String? = null,
    val isLive: Boolean = false,
    val description: String? = null,
    val subscriberCount: String? = null,
    val descriptionLinks: List<RichLink> = emptyList(),
    val publishedAtMs: Long? = null,
    val dismissal: DismissalTokens? = null
) {
    val videoId: String get() {
        return when {
            url.contains("/shorts/") -> url.substringAfter("/shorts/").substringBefore("?")
            url.contains("watch?v=") -> url.substringAfter("watch?v=").substringBefore("&")
            else -> url.substringAfterLast("/").substringBefore("?")
        }
    }
    val id: String get() = videoId
    val safeThumb: String get() = thumbnailUrl ?: "https://i.ytimg.com/vi/$videoId/hqdefault.jpg"

    val highResThumbnailUrl: String?
        get() = thumbnailUrl?.let { url ->
            when {
                url.contains("ytimg.com") || url.contains("youtube.com") -> {
                    url.replace("mqdefault", "maxresdefault")
                       .replace("hqdefault", "maxresdefault")
                       .replace("sddefault", "maxresdefault")
                }
                else -> url
            }
        }

    val formattedDuration: String
        get() {
            if (isLive) return "LIVE"
            if (duration <= 0) return ""
            val hours = duration / 3600
            val minutes = (duration % 3600) / 60
            val seconds = duration % 60
            return if (hours > 0) {
                String.format("%d:%02d:%02d", hours, minutes, seconds)
            } else {
                String.format("%d:%02d", minutes, seconds)
            }
        }

    companion object {
        fun formatViewCount(count: Long?): String {
            if (count == null || count < 0) return ""
            return when {
                count >= 1_000_000_000 -> String.format("%.1fB views", count / 1_000_000_000.0)
                count >= 1_000_000 -> String.format("%.1fM views", count / 1_000_000.0)
                count >= 1_000 -> String.format("%.1fK views", count / 1_000.0)
                else -> "$count views"
            }
        }

        fun formatRelativeTime(publishedAtMs: Long, nowMs: Long = System.currentTimeMillis()): String {
            val seconds = ((nowMs - publishedAtMs) / 1000).coerceAtLeast(0)
            val units = listOf(
                31_536_000L to "year",
                2_592_000L to "month",
                604_800L to "week",
                86_400L to "day",
                3_600L to "hour",
                60L to "minute"
            )
            for ((size, label) in units) {
                if (seconds >= size) {
                    val value = seconds / size
                    return "$value $label${if (value == 1L) "" else "s"} ago"
                }
            }
            return "just now"
        }
    }
}

data class DismissalTokens(
    val notInterested: String? = null,
    val notInterestedUndo: String? = null,
    val blockChannel: String? = null,
    val blockChannelUndo: String? = null
)

data class VideoQuality(
    val resolution: String,
    val url: String,
    val format: String? = null,
    val isDASH: Boolean = false,
    val audioUrl: String? = null,
    val isLive: Boolean = false,
    val sourceAspectRatio: Float? = null
) {
    val isPortrait: Boolean get() = sourceAspectRatio?.let { it > 0f && it < 1f } ?: false
}

data class VideoDetails(
    val qualities: List<VideoQuality>,
    val relatedVideos: List<VideoItem>,
    val updatedVideoItem: VideoItem? = null
)

data class VideoChapter(
    val title: String,
    val startMs: Long,
    val thumbnailUrl: String? = null
)

data class WatchNextData(
    val engagement: VideoEngagement?,
    val updatedVideoItem: VideoItem?,
    val relatedVideos: List<VideoItem>,
    val chapters: List<VideoChapter> = emptyList(),
    val liveChatContinuation: String? = null
)

data class CaptionTrack(
    val languageCode: String,
    val name: String,
    val baseUrl: String,
    val isAutoGenerated: Boolean = false
) {
    val vttUrl: String
        get() = baseUrl
            .replace(FMT_PARAM, "")
            .replace(TLANG_PARAM, "") + "&fmt=vtt"

    private companion object {
        val FMT_PARAM = Regex("&fmt=[^&]*")
        val TLANG_PARAM = Regex("&tlang=[^&]*")
    }
}

data class VideoFeedPage(
    val videos: List<VideoItem>,
    val continuation: String? = null
)

data class VideoPlaylist(
    val playlistId: String,
    val title: String,
    val thumbnailUrl: String? = null,
    val videoCountText: String? = null,
    val subtitle: String? = null
)
